image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install poetry
  - poetry --version
  - poetry install -vv

test:
  script:
    - poetry run task build
