stages:
  - lint
  - build
  - pages

apache_licenses_check:
  stage: lint
  image: registry.gitlab.com/ai-r/apache-license-checker:latest
  script:
    - apache-license-checker

build:
  stage: build
  image: python:latest
  before_script:
    - pip install poetry
    - poetry --version
    - poetry install -vv
  script:
    - poetry run task build
  artifacts:
    paths:
      - public

pages:
  stage: pages
  script:
    - echo "Using build artifacts from previous stage"
  artifacts:
    paths:
      - public
  only:
    - main
