# from .editorconfig the following are retrieved
# - end_of_line
# - indent_style
# - indent_size/tab_width
# - max_line_length
# Keeping this file around as it signal configured editor to use prettier for formatting.
