site_name: Cogment
site_url: https://docs.cogment.ai
repo_url: https://github.com/cogment/cogment-doc
site_dir: public
docs_dir: src
theme:
  name: "readthedocs"

nav:
  - "Introduction":
      - "Overview": "index.md"
      - "Installation & Setup": "introduction/installation.md"
  - "Support":
      - "Community channels": "support/community-channels.md"
  - "Concepts":
      - "Core Concepts": "concepts/core-concepts.md"
      - "Glossary": "concepts/glossary.md"
  - "Cogment":
      - "Tutorial":
          - "Introduction": "cogment/tutorial/introduction.md"
          - "Step 1: Bootstrap a Cogment app": "cogment/tutorial/1-bootstrap-and-data-structures.md"
          - "Step 2: Implement actor and environment": "cogment/tutorial/2-random-player.md"
          - "Step 3: Introduce rewards": "cogment/tutorial/3-rewards.md"
          - "Step 4: Create a heuristic player": "cogment/tutorial/4-heuristic-player.md"
          - "Step 5: Add a human player in the loop": "cogment/tutorial/5-human-player.md"
      - "Cogment API Guide": "cogment/cogment-api-guide.md"
      - "Cogment API Reference":
          - "cogment.yaml": "cogment/cogment-api-reference/cogment-yaml.md"
          - "python": "cogment/cogment-api-reference/python.md"
          - "Javascript/Typescript SDK":
              - "Modules": "cogment/cogment-api-reference/javascript/modules.md"
              - "Class: ActorSession": "cogment/cogment-api-reference/javascript/classes/actorsession.md"
              - "Class: CogmentService": "cogment/cogment-api-reference/javascript/classes/cogmentservice.md"
              - "Class: TrialController": "cogment/cogment-api-reference/javascript/classes/trialcontroller.md"
              - "Enum: EventType": "cogment/cogment-api-reference/javascript/enums/eventtype.md"
              - "Interface: CogmentYaml": "cogment/cogment-api-reference/javascript/interfaces/cogmentyaml.md"
              - "Interface: CogmentYamlActor": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamlactor.md"
              - "Interface: CogmentYamlActorClass": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamlactorclass.md"
              - "Interface: CogmentYamlDatalog": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamldatalog.md"
              - "Interface: CogmentYamlTrialParameters": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamltrialparameters.md"
              - "Interface: CogSettings": "cogment/cogment-api-reference/javascript/interfaces/cogsettings.md"
              - "Interface: CogSettingsActorClass": "cogment/cogment-api-reference/javascript/interfaces/cogsettingsactorclass.md"
              - "Interface: CreateServiceOptions": "cogment/cogment-api-reference/javascript/interfaces/createserviceoptions.md"
              - "Interface: Event": "cogment/cogment-api-reference/javascript/interfaces/event.md"
              - "Interface: Reward": "cogment/cogment-api-reference/javascript/interfaces/reward.md"
              - "Interface: SendMessageOptions": "cogment/cogment-api-reference/javascript/interfaces/sendmessageoptions.md"
              - "Interface: TrialActor": "cogment/cogment-api-reference/javascript/interfaces/trialactor.md"
      - "Cogment Low Level API Guide":
          - "Overview": "cogment/cogment-low-level-api-guide/overview.md"
          - "gRPC API Reference": "cogment/cogment-low-level-api-guide/grpc.md"
  - "Deployment Guide":
      - "Local Deployment": "deployment-guide/local-deployement.md"
      # - "Cloud Deployment": "deployment-guide/cloud-deployement.md" # out-of-scope for É‘
  - "License": "license.md"
