site_name: Cogment User Documentation
site_url: https://docs.cogment.ai
repo_url: https://github.com/cogment/cogment-doc
edit_uri: "edit/main/src/"
site_dir: public
docs_dir: src

site_description: Cogment user documentation - Cogment is an innovative open source AI platform designed to leverage the advent of AI to benefit humankind through human-AI collaboration
site_author: AI Redefined
copyright: Copyright 2021 AI Redefined Inc. <dev+cogment@ai-r.com>

google_analytics: ["UA-146998765-2", "doc.cogment.ai"]

theme:
  name: "material"
  language: en
  logo: "images/cogment_logo.png"
  favicon: "images/cogment_favicon.png"
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cogment
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AI_Redefined
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ai-r

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
extra_css:
  - style/theme.css
  # Defines the highlight.js theme used (cf. https://highlightjs.org/static/demo/)
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/github.min.css

nav:
  - "Introduction":
      - "Overview": "index.md"
      - "Installation & Setup": "introduction/installation.md"
  - "Support":
      - "Community channels": "support/community-channels.md"
  - "Concepts":
      - "Core Concepts": "concepts/core-concepts.md"
      - "Glossary": "concepts/glossary.md"
  - "Cogment APIs":
      - "Tutorial":
          - "Introduction": "cogment/tutorial/introduction.md"
          - "Step 1: Bootstrap a Cogment app": "cogment/tutorial/1-bootstrap-and-data-structures.md"
          - "Step 2: Implement actor and environment": "cogment/tutorial/2-random-player.md"
          - "Step 3: Introduce rewards": "cogment/tutorial/3-rewards.md"
          - "Step 4: Create a heuristic player": "cogment/tutorial/4-heuristic-player.md"
          - "Step 5: Add a human player in the loop": "cogment/tutorial/5-human-player.md"
          - "Step 6: Implement a web client for the human player": "cogment/tutorial/6-web-client.md"
          - "Step 7: Add a player trained with Reinforcement Learning using DQN": "cogment/tutorial/7-dqn-player.md"
      - "API Guide": "cogment/cogment-api-guide.md"
      - "API Reference":
          - "Spec file (cogment.yaml)": "cogment/cogment-api-reference/cogment-yaml.md"
          - "Parameters": "cogment/cogment-api-reference/parameters.md"
          - "Python SDK": "cogment/cogment-api-reference/python.md"
          - "Javascript/Typescript SDK": "cogment/cogment-api-reference/javascript.md"
      - "Low Level API Reference":
          - "Overview": "cogment/cogment-low-level-api-guide/overview.md"
          - "gRPC API Reference": "cogment/cogment-low-level-api-guide/grpc.md"
      - "Implementation recipes": "cogment/implementation-recipes/implementation-recipes.md"
  - "Cogment Components":
      - "CLI": "cogment-components/cli/cli.md"
      - "Orchestrator": "cogment-components/orchestrator/orchestrator.md"
      - "Model Registry": "cogment-components/model-registry/model-registry.md"
      - "Trial Datastore": "cogment-components/trial-datastore/trial-datastore.md"
      - "Metrics & Dashboard": "cogment-components/dashboard/metrics-and-dashboard.md"

  #- "Deployment Guide":
  # - "Local Deployment": "deployment-guide/local-deployement.md"
  # - "Cloud Deployment": "deployment-guide/cloud-deployement.md" # out-of-scope for É‘
  - "License": "license.md"
