site_name: Cogment
site_dir: public
docs_dir: src
theme:
  name: "readthedocs"

nav:
  - "Introduction":
      - "Overview": "index.md"
      - "Installation & Setup": "introduction/installation.md"
  - "Support":
      - "Community channels": "support/community-channels.md"
      # - "FAQ": "support/faq.md" # out-of-scope for ɑ
      # - "Troubleshooting": "support/troubleshooting.md" # out-of-scope for ɑ
  - "Concepts":
      - "Core Concepts": "concepts/core-concepts.md"
      - "Glossary": "concepts/glossary.md"
  - "Cogment":
      - "Getting Started": "cogment/getting-started.md"
      # - "Tutorial": # nice-to-have for ɑ
      #     - "Intro": "cogment/tutorial/intro.md"
      #     - "Step 1 : Create a new Trial": "cogment/tutorial/step1/index.md"
      #     - "Step 2 : Implement our components": "cogment/tutorial/step2/index.md"
      #     - "Step 3 : Upgrade our components": "cogment/tutorial/step3/index.md"
      #     - "Step 4 : Create a friendly UI": "cogment/tutorial/step4/index.md"
      #     - "Step 5 : Dataset and Results": "cogment/tutorial/step5/index.md"
      - "Cogment API Guide": "cogment/cogment-api-guide.md"
      - "Cogment API Reference":
          - "cogment.yaml": "cogment/cogment-api-reference/cogment-yaml.md"
          - "python": "cogment/cogment-api-reference/python.md"
          # - "javascript": "cogment/cogment-api-reference/javascript.md" # out-of-scope for ɑ
      - "Agent Toolbox Guide":
          - "Introduction": "cogment/cogment-agent-toolbox-guide/agent-toolbox-introduction.md"
      - "Cogment Low Level API Guide":
          - "Overview": "cogment/cogment-low-level-api-guide/overview.md"
          - "gRPC API Reference": "cogment/cogment-low-level-api-guide/grpc.md"
  - "Deployment Guide":
      - "Local Deployment": "deployment-guide/local-deployement.md"
      # - "Cloud Deployment": "deployment-guide/cloud-deployement.md" # out-of-scope for ɑ
  - "License": "license.md"
