site_name: Cogment User Documentation
site_url: https://docs.cogment.ai
repo_url: https://github.com/cogment/cogment-doc
edit_uri: "edit/main/src/"
site_dir: public
docs_dir: src

site_description: Cogment user documentation - Cogment is an innovative open source AI platform designed to leverage the advent of AI to benefit humankind through human-AI collaboration
site_author: AI Redefined
copyright: Copyright 2021 AI Redefined Inc. <dev+cogment@ai-r.com>

google_analytics: ["UA-146998765-2", "doc.cogment.ai"]

theme:
  name: "material"
  language: en
  logo: "images/cogment_logo.png"
  favicon: "images/cogment_favicon.png"
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cogment
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AI_Redefined
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ai-r

extra_css:
  - style/theme.css

nav:
  - "Introduction":
      - "Overview": "index.md"
      - "Installation & Setup": "introduction/installation.md"
  - "Support":
      - "Community channels": "support/community-channels.md"
  - "Concepts":
      - "Core Concepts": "concepts/core-concepts.md"
      - "Glossary": "concepts/glossary.md"
  - "Cogment APIs":
      - "Tutorial":
          - "Introduction": "cogment/tutorial/introduction.md"
          - "Step 1: Bootstrap a Cogment app": "cogment/tutorial/1-bootstrap-and-data-structures.md"
          - "Step 2: Implement actor and environment": "cogment/tutorial/2-random-player.md"
          - "Step 3: Introduce rewards": "cogment/tutorial/3-rewards.md"
          - "Step 4: Create a heuristic player": "cogment/tutorial/4-heuristic-player.md"
          - "Step 5: Add a human player in the loop": "cogment/tutorial/5-human-player.md"
          - "Step 6: Implement a web client for the human player": "cogment/tutorial/6-web-client.md"
          - "Step 7: Add a player trained with Reinforcement Learning using DQN": "cogment/tutorial/7-dqn-player.md"
      - "API Guide": "cogment/cogment-api-guide.md"
      - "API Reference":
          - "cogment.yaml": "cogment/cogment-api-reference/cogment-yaml.md"
          - "python": "cogment/cogment-api-reference/python.md"
          - "Javascript/Typescript SDK":
              - "Modules": "cogment/cogment-api-reference/javascript/modules.md"
              - "Class: ActorSession": "cogment/cogment-api-reference/javascript/classes/actorsession.md"
              - "Class: CogmentService": "cogment/cogment-api-reference/javascript/classes/cogmentservice.md"
              - "Class: TrialController": "cogment/cogment-api-reference/javascript/classes/trialcontroller.md"
              - "Enum: EventType": "cogment/cogment-api-reference/javascript/enums/eventtype.md"
              - "Interface: CogmentYaml": "cogment/cogment-api-reference/javascript/interfaces/cogmentyaml.md"
              - "Interface: CogmentYamlActor": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamlactor.md"
              - "Interface: CogmentYamlActorClass": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamlactorclass.md"
              - "Interface: CogmentYamlDatalog": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamldatalog.md"
              - "Interface: CogmentYamlTrialParameters": "cogment/cogment-api-reference/javascript/interfaces/cogmentyamltrialparameters.md"
              - "Interface: CogSettings": "cogment/cogment-api-reference/javascript/interfaces/cogsettings.md"
              - "Interface: CogSettingsActorClass": "cogment/cogment-api-reference/javascript/interfaces/cogsettingsactorclass.md"
              - "Interface: CreateServiceOptions": "cogment/cogment-api-reference/javascript/interfaces/createserviceoptions.md"
              - "Interface: Event": "cogment/cogment-api-reference/javascript/interfaces/event.md"
              - "Interface: Reward": "cogment/cogment-api-reference/javascript/interfaces/reward.md"
              - "Interface: SendMessageOptions": "cogment/cogment-api-reference/javascript/interfaces/sendmessageoptions.md"
              - "Interface: TrialActor": "cogment/cogment-api-reference/javascript/interfaces/trialactor.md"
      - "Low Level API Reference":
          - "Overview": "cogment/cogment-low-level-api-guide/overview.md"
          - "gRPC API Reference": "cogment/cogment-low-level-api-guide/grpc.md"
  - "Cogment Components":
      - "CLI": "cogment-components/cli/cli.md"
      - "Orchestrator": "cogment-components/orchestrator/orchestrator.md"
      - "Model Registry": "cogment-components/model-registry/model-registry.md"
      - "Trial Datastore": "cogment-components/trial-datastore/trial-datastore.md"
      - "Metrics & Dashboard": "cogment-components/dashboard/metrics-and-dashboard.md"

  #- "Deployment Guide":
  # - "Local Deployment": "deployment-guide/local-deployement.md"
  # - "Cloud Deployment": "deployment-guide/cloud-deployement.md" # out-of-scope for É‘
  - "License": "license.md"
